
export enum PermissaoEnum{

  ROLE_USUARIO_CONSULTAR,
  ROLE_USUARIO_REGISTRAR,
  ROLE_USUARIO_DELETAR,

  ROLE_PERMISSAO_CONSULTAR,
  ROLE_PERMISSAO_REGISTRAR,
  ROLE_PREMISSAO_DELETAR,

  ROLE_FORNECEDOR_CONSULTAR,
  ROLE_FORNECEDOR_REGISTRAR,
  ROLE_FORNECEDOR_DELETAR,

  ROLE_ESTADO_CONSULTAR,
  ROLE_ESTADO_REGISTRAR,
  ROLE_ESTADO_DELETAR,

  ROLE_CIDADE_CONSULTAR,
  ROLE_CIDADE_REGISTRAR,
  ROLE_CIDADE_DELETAR,

  ROLE_TIPO_EMBALAGEM_CONSULTAR,
  ROLE_TIPO_EMBALAGEM_REGISTRAR,
  ROLE_TIPO_EMBALAGEM_DELETAR,

  ROLE_PRODUTO_CONSULTAR,
  ROLE_PRODUTO_REGISTRAR,
  ROLE_PRODUTO_DELETAR
}
